Fix stuck in loop while looking for new interfaces
smlng/unstrung pull request #1
Opened 2018-12-20 15:08 UTC by pokgak

2019-01-08 09:06 UTC, smlng requested changes
minor nit, otherwise fixes the issue we found

2019-01-08 09:06 UTC, smlng commented on lib/libndmgmt/iface.cpp
> +        iface = next;
you can simplify this and use `iface = iface->next;` here omitting the extra variable

2019-01-09 08:18 UTC, smlng approved these changes

2019-01-09 18:04 UTC, pokgak commented
Squashed.

2019-01-11 09:14 UTC, smlng commented
please rebase on latest master to make Travis-CI happy

2019-01-12 01:05 UTC, pokgak commented
Rebased on latest master. Checks all green now.

2019-01-14 15:37 UTC, merged